Repository WebPlatformForEmbedded/WPEWebKit, pull requests merged in 2023-03, with the labels that each got.

#1046 Cache video quality stats
  Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
  Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.h
Labels: wpe-2.28

#1062 [MSE][GStreamer]: Fix artifacts on STV at the end of the movie
  Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp
Labels: wpe-2.22

#1060 wpe-2.28 flush improvements
  Source/WebCore/platform/graphics/gstreamer/mse/PlaybackPipeline.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/SourceBufferPrivateGStreamer.cpp
Labels: wpe-2.28

#1066 Fix MediaPlayerPrivateHolePunch:setSize() method name
  Source/WebCore/platform/graphics/holepunch/MediaPlayerPrivateHolePunch.h
Labels: wpe-2.38
