Repository WebPlatformForEmbedded/WPEWebKit, pull requests merged in 2023-02, with the labels that each got.

#1010 Add missing 'Coded Frame Removal' algorithm step in SourceBuffer
  Source/WebCore/Modules/mediasource/SourceBuffer.cpp
Labels: wpe-2.28

#1029 Add a provision in WebKitURIResponse to check if the response is from…
  Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
  Source/WebKit/Shared/API/glib/WebKitURIResponsePrivate.h
  Source/WebKit/UIProcess/API/glib/WebKitResponsePolicyDecision.cpp
  Source/WebKit/UIProcess/API/wpe/WebKitURIResponse.h
Labels: wpe-2.38

#1030 Fix build with touch events disabled
  Source/WebKit/UIProcess/API/wpe/WPEView.cpp
Labels: wpe-2.38

#1036 [libwebrtc] fix build without pulseaudio
  Source/ThirdParty/libwebrtc/CMakeLists.txt
  Source/ThirdParty/libwebrtc/cmake/FindLibPulse.cmake
Labels: wpe-2.38

#1038 Fix crash in TextureMapperPlatformLayerProxyGL::invalidate
  Source/WebCore/platform/graphics/texmap/TextureMapperPlatformLayerProxyGL.cpp
Labels: wpe-2.38

#1040 [GStreamer][EME] Ignore case sensitive when comparing UUID
  Source/WebCore/platform/graphics/gstreamer/eme/GStreamerEMEUtilities.h
Labels: wpe-2.22
