Repository WebPlatformForEmbedded/WPEWebKit, pull requests merged in 2023-09, with the labels that each got.

#1155 [wpe-2.28] Expose API for sending memory pressure events
  Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
  Source/WebKit/UIProcess/API/wpe/WebKitWebView.h
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
Labels: wpe-2.28

#1158 Pgorszkowski/2.42/optimize binary size
  Source/cmake/OptionsWPE.cmake
Labels: wpe-2.42

#1159 Pgorszkowski/2.42/webprocess responsiveness
  Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
  Source/WebKit/UIProcess/API/glib/WebKitWebView.h.in
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
Labels: wpe-2.42

#1161 Add a setting to allow closing windows from scripts
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/page/LocalDOMWindow.cpp
  Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp
  Source/WebKit/UIProcess/API/glib/WebKitSettings.h.in
Labels: wpe-2.42

#1162 Add setting to enable/disable directory upload
  Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp
  Source/WebKit/UIProcess/API/glib/WebKitSettings.h.in
Labels: wpe-2.42

#1163 webinspector changes
  Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorServer.cpp
  Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorUtils.cpp
  Source/WebInspectorUI/UserInterface/Views/DOMTreeOutline.css
  Source/WebInspectorUI/UserInterface/Views/GradientSlider.css
  Source/WebInspectorUI/UserInterface/Views/HoverMenu.css
  Source/WebInspectorUI/UserInterface/Views/Slider.css
  Source/WebInspectorUI/UserInterface/Views/SourceCodeTextEditor.css
  Source/WebInspectorUI/UserInterface/Views/TextEditor.css
  Source/WebKit/UIProcess/API/glib/WebKitInitialize.cpp
  Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.cpp
  Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorClient.h
  Source/WebKit/UIProcess/Inspector/glib/RemoteInspectorHTTPServer.cpp
Labels: wpe-2.42

#1164 Add provision to allow insecure content
  Source/WebKit/UIProcess/API/glib/WebKitSettings.cpp
  Source/WebKit/UIProcess/API/glib/WebKitSettings.h.in
Labels: wpe-2.42

#1168 Add a property to WebKitWebsiteDataManager to set the LocalStorage qu…
  Source/WebCore/page/Settings.yaml
  Source/WebCore/storage/StorageNamespaceProvider.cpp
  Source/WebCore/storage/StorageNamespaceProvider.h
  Source/WebCore/testing/Internals.cpp
  Source/WebKit/NetworkProcess/NetworkProcess.h
  Source/WebKit/NetworkProcess/NetworkProcessCreationParameters.h
  Source/WebKit/NetworkProcess/NetworkProcessCreationParameters.serialization.in
  Source/WebKit/NetworkProcess/soup/NetworkProcessSoup.cpp
  Source/WebKit/NetworkProcess/storage/LocalStorageManager.cpp
  Source/WebKit/Shared/WebPageCreationParameters.h
  Source/WebKit/Shared/WebPageCreationParameters.serialization.in
  Source/WebKit/UIProcess/API/glib/WebKitWebsiteDataManager.cpp
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebProcessPool.h
  Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.h
  Source/WebKit/UIProcess/WebsiteData/WebsiteDataStoreConfiguration.cpp
  Source/WebKit/UIProcess/WebsiteData/WebsiteDataStoreConfiguration.h
  Source/WebKit/UIProcess/soup/WebProcessPoolSoup.cpp
  Source/WebKit/WebProcess/WebPage/WebPage.cpp
Labels: wpe-2.42

#1173 Disable caching of XHR ArrayBuffer and/or env variable
  Source/WebCore/xml/XMLHttpRequest.cpp
Labels: wpe-2.42

#1170 [wpe-2.38] Expose API for sending memory pressure events
  Source/WebKit/UIProcess/API/glib/WebKitWebView.cpp
  Source/WebKit/UIProcess/API/wpe/WebKitWebView.h
  Source/WebKit/UIProcess/WebPageProxy.cpp
  Source/WebKit/UIProcess/WebPageProxy.h
Labels: wpe-2.38

#1174 Jettison on top level navigation
  Source/WebCore/loader/FrameLoader.cpp
  Source/WebCore/page/MemoryRelease.cpp
Labels: wpe-2.42

#1176 Add a provision in WebKitURIResponse to check if the response is from…
  Source/WebKit/Shared/API/glib/WebKitURIResponse.cpp
  Source/WebKit/Shared/API/glib/WebKitURIResponsePrivate.h
  Source/WebKit/UIProcess/API/glib/WebKitResponsePolicyDecision.cpp
  Source/WebKit/UIProcess/API/glib/WebKitURIResponse.h.in
Labels: wpe-2.42

#1178 Build fix after 160450@main by guarding showRenderTree
  Source/WebCore/page/LocalFrameViewLayoutContext.cpp
Labels: wpe-2.42

#1179 Added option to enable logs
  Source/cmake/OptionsWPE.cmake
  Source/cmake/WebKitFeatures.cmake
Labels: wpe-2.42

#1180 Take into account scaling operations when deciding backingStore scale…
  Source/WebCore/platform/graphics/nicosia/NicosiaAnimation.cpp
  Source/WebCore/platform/graphics/nicosia/NicosiaAnimation.h
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp
  Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.h
Labels: wpe-2.42

#1181 provision wal_autocheckpoint to prevent the log file growing to large…
  Source/WebCore/platform/sql/SQLiteDatabase.cpp
  Source/WebKit/NetworkProcess/storage/SQLiteStorageArea.cpp
Labels: wpe-2.42

#1182 Control on-disk cache size with env var WPE_DISK_CACHE_SIZE
  Source/WebKit/Shared/CacheModel.cpp
Labels: wpe-2.42

#1183 wpe-2.38 WebInspectorUI: Fix base64 encoded files saving
  Source/WebInspectorUI/UserInterface/Base/BrowserInspectorFrontendHost.js
Labels: wpe-2.38

#1187 Pgorszkowski/2.42/accessibility patches
  Source/WebCore/PlatformWPE.cmake
  Source/WebCore/SourcesWPE.txt
  Source/WebCore/accessibility/AXObjectCache.h
  Source/WebCore/accessibility/AccessibilityList.cpp
  Source/WebCore/accessibility/AccessibilityNodeObject.cpp
  Source/WebCore/accessibility/AccessibilityObject.cpp
  Source/WebCore/accessibility/AccessibilityObject.h
  Source/WebCore/accessibility/AccessibilityObjectInterface.h
  Source/WebCore/accessibility/AccessibilityTableColumn.cpp
  Source/WebCore/accessibility/AccessibilityTableHeaderContainer.cpp
  Source/WebCore/accessibility/atk/AXObjectCacheAtk.cpp
  Source/WebCore/accessibility/atk/AccessibilityObjectAtk.cpp
  Source/WebCore/accessibility/atk/WebKitAccessible.cpp
  Source/WebCore/accessibility/atk/WebKitAccessible.h
  Source/WebCore/accessibility/atk/WebKitAccessibleHyperlink.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleHyperlink.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceAction.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceAction.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceComponent.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceComponent.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceDocument.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceDocument.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceEditableText.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceEditableText.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceHyperlinkImpl.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceHyperlinkImpl.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceHypertext.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceHypertext.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceImage.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceImage.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceSelection.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceSelection.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceTable.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceTable.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceTableCell.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceTableCell.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceText.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceText.h
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceValue.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleInterfaceValue.h
  Source/WebCore/accessibility/atk/WebKitAccessibleUtil.cpp
  Source/WebCore/accessibility/atk/WebKitAccessibleUtil.h
  Source/WebCore/accessibility/atspi/AccessibilityObjectAtspi.cpp
  Source/WebCore/dom/Range.h
  Source/WebCore/editing/FrameSelection.h
  Source/WebCore/editing/TextIterator.cpp
  Source/WebCore/editing/atk/FrameSelectionAtk.cpp
  Source/WebKit/PlatformWPE.cmake
  Source/cmake/OptionsWPE.cmake
Labels: wpe-2.42

#1200 [WebInspectorUI] Implemented Web Inspector Save Function
  Source/WebInspectorUI/UserInterface/Base/BrowserInspectorFrontendHost.js
Labels: wpe-2.28

#1201 Web Inspector: Uncaught Exception: Right side of assignment cannot be…
  Source/WebInspectorUI/ChangeLog
  Source/WebInspectorUI/UserInterface/Views/QuickConsole.js
Labels: wpe-2.28
