Repository WebPlatformForEmbedded/WPEWebKit, pull requests merged in 2025-04, with the labels that each got.

#1478 [GStreamer][MSE] ignore 'closedcaption/' tracks
  Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp
  Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.h
Labels: upstream, wpe-2.46

#1484 [WebInspector] make customizable limit for content resources kept for…
  Source/WTF/Scripts/Preferences/WebPreferences.yaml
  Source/WebCore/inspector/NetworkResourcesData.cpp
  Source/WebCore/inspector/NetworkResourcesData.h
  Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp
  Source/WebCore/inspector/agents/InspectorNetworkAgent.h
  Source/WebCore/inspector/agents/page/PageNetworkAgent.cpp
  Source/WebCore/inspector/agents/worker/WorkerNetworkAgent.cpp
Labels: wpe-2.38

#1488 [2.38][GStreamerQuirks] Add isPlatformSupported() impl
  Source/WebCore/platform/gstreamer/GStreamerQuirkAmLogic.cpp
  Source/WebCore/platform/gstreamer/GStreamerQuirkAmLogic.h
  Source/WebCore/platform/gstreamer/GStreamerQuirkBroadcom.cpp
  Source/WebCore/platform/gstreamer/GStreamerQuirkBroadcom.h
  Source/WebCore/platform/gstreamer/GStreamerQuirkRealtek.cpp
  Source/WebCore/platform/gstreamer/GStreamerQuirkRealtek.h
  Source/WebCore/platform/gstreamer/GStreamerQuirkRialto.cpp
  Source/WebCore/platform/gstreamer/GStreamerQuirkRialto.h
  Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.cpp
  Source/WebCore/platform/gstreamer/GStreamerQuirkWesteros.h
  Source/WebCore/platform/gstreamer/GStreamerQuirks.cpp
Labels: wpe-2.38

#1493 [WebInspector] minimize the number of data kept in m_requestIdToResou…
  Source/WTF/Scripts/Preferences/WebPreferences.yaml
  Source/WebCore/inspector/InspectorFrontendHost.cpp
  Source/WebCore/inspector/NetworkResourcesData.cpp
  Source/WebCore/inspector/NetworkResourcesData.h
  Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp
  Source/WebCore/inspector/agents/InspectorNetworkAgent.h
  Source/WebCore/inspector/agents/page/PageNetworkAgent.cpp
  Source/WebCore/inspector/agents/worker/WorkerNetworkAgent.cpp
Labels: wpe-2.38

#1492 [SpeechSynthesis] Emit error event for all cancelled utterances
  LayoutTests/fast/speechsynthesis/speech-synthesis-cancel-expected.txt
  LayoutTests/fast/speechsynthesis/speech-synthesis-cancel.html
  Source/WebCore/Modules/speech/SpeechSynthesis.cpp
Labels: wpe-2.38

#1495 [WebInspector] make customizable limit for content resources kept for…
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/inspector/NetworkResourcesData.cpp
  Source/WebCore/inspector/NetworkResourcesData.h
  Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp
  Source/WebCore/inspector/agents/InspectorNetworkAgent.h
  Source/WebCore/inspector/agents/page/PageNetworkAgent.cpp
  Source/WebCore/inspector/agents/worker/WorkerNetworkAgent.cpp
Labels: wpe-2.46

#1496 [WebInspector] minimize the number of data kept in m_requestIdToResou…
  Source/WTF/Scripts/Preferences/UnifiedWebPreferences.yaml
  Source/WebCore/inspector/InspectorFrontendHost.cpp
  Source/WebCore/inspector/NetworkResourcesData.cpp
  Source/WebCore/inspector/NetworkResourcesData.h
  Source/WebCore/inspector/agents/InspectorNetworkAgent.cpp
  Source/WebCore/inspector/agents/InspectorNetworkAgent.h
  Source/WebCore/inspector/agents/page/PageNetworkAgent.cpp
  Source/WebCore/inspector/agents/worker/WorkerNetworkAgent.cpp
Labels: wpe-2.46

#1497 [SOUP] WPENetworkProcess crashed on process exit
  Source/WebCore/platform/network/soup/SoupNetworkSession.cpp
Labels: wpe-2.38
